site_name: DSCTeX
repo_url: https://github.com/eldridgejm/dsctex
edit_uri: edit/main/docs/
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
